package com.oceanguard.ai.inference

import com.oceanguard.ai.data.DebrisMaterial
import com.oceanguard.ai.data.DetectionSession
import com.oceanguard.ai.data.HealthTrend
import java.text.SimpleDateFormat
import java.util.Locale

/**
 * Deterministic template-based report builders used as fallback when the
 * VLM is unavailable. Extracted from [ReportGenerator] to keep file sizes
 * manageable.
 */
internal object ReportTemplateBuilder {

    private val DATE_FORMAT = SimpleDateFormat("yyyy-MM-dd HH:mm", Locale.getDefault())
    private val DAY_FORMAT = SimpleDateFormat("yyyy-MM-dd", Locale.getDefault())

    private val LANGUAGE_NAMES = mapOf(
        "en" to "English", "es" to "Spanish", "fr" to "French",
        "de" to "German", "it" to "Italian", "pt" to "Portuguese",
    )

    // -----------------------------------------------------------------
    // Generic (non-zone) template report
    // -----------------------------------------------------------------

    fun buildTemplateReport(
        sessions: List<DetectionSession>,
        language: String,
    ): String {
        val totalDebris = sessions.sumOf { it.totalCount }
        val avgHealth = sessions.map { it.healthScore }.average()
        val sessionCount = sessions.size
        val materialMap = buildMaterialMap(sessions)
        val dominantMaterial = materialMap.maxByOrNull { it.value }
        val highRiskCount = countHighRisk(sessions)
        val dateRange = formatDateRange(sessions)
        val healthLabel = healthLabel(avgHealth)

        val materialBreakdownStr = formatMaterialBreakdown(materialMap)
        val locationsWithData = sessions.mapNotNull { it.location }
        val locationNote = if (locationsWithData.isNotEmpty()) {
            "GPS data was recorded for ${locationsWithData.size} of $sessionCount sessions."
        } else {
            "No GPS coordinates were recorded for this survey."
        }

        val dominantMaterialSentence = dominantMaterial?.let { (mat, count) ->
            "The most prevalent debris material was **${mat.name.replace("_", " ")}** ($count items), " +
                "which requires immediate targeted intervention due to its persistence in marine environments."
        } ?: "No single dominant material was identified across the survey sessions."

        val riskSentence = if (highRiskCount > 0) {
            "A total of **$highRiskCount high-risk item(s)** were detected, posing elevated threats " +
                "of entanglement, ingestion, or chemical contamination to marine fauna."
        } else {
            "No high-risk items were identified in this survey period."
        }

        return buildString {
            appendLine("# OceanGuard AI — Marine Debris Survey Report")
            appendLine()
            appendLine("**Survey period:** $dateRange")
            appendLine("**Sessions analysed:** $sessionCount")
            appendLine("**Generated by:** OceanGuard AI v1.0 (Template Report)")
            appendLine()
            appendLine("---")
            appendLine()
            appendLine("## Overview")
            appendLine()
            appendLine(
                "This report summarises the findings from **$sessionCount underwater debris detection " +
                "session(s)** conducted between $dateRange. A total of **$totalDebris debris item(s)** " +
                "were identified across all survey images. The mean ecosystem health score for the " +
                "surveyed area is **${String.format("%.1f", avgHealth)}/100**, classified as **$healthLabel**, " +
                "indicating ${healthDescription(avgHealth)}."
            )
            appendLine()
            appendLine(locationNote)
            appendLine()
            appendLine("---")
            appendLine()
            appendLine("## Key Findings")
            appendLine()
            appendLine("### Debris Composition")
            appendLine()
            appendLine(dominantMaterialSentence)
            appendLine()
            appendLine("**Full material breakdown:** $materialBreakdownStr")
            appendLine()
            appendLine("### Risk Assessment")
            appendLine()
            appendLine(riskSentence)
            appendLine()
            if (avgHealth < 60) {
                appendLine(
                    "> **Area of Concern:** The ecosystem health score of " +
                    "${String.format("%.1f", avgHealth)}/100 indicates significant anthropogenic stress. " +
                    "Intervention is recommended as a priority."
                )
                appendLine()
            }
            appendLine("---")
            appendLine()
            appendLine("## Recommendations")
            appendLine()
            val recs = buildRecommendations(dominantMaterial?.key, avgHealth, highRiskCount)
            recs.forEachIndexed { i, rec -> appendLine("${i + 1}. $rec") }
            appendLine()
            appendLine("---")
            appendLine()
            appendLine("*This report was generated automatically by OceanGuard AI. For AI-assisted narrative " +
                "analysis, deploy the AI model to the device and regenerate.*")
        }.trimEnd()
    }

    // -----------------------------------------------------------------
    // Zone-based temporal template report
    // -----------------------------------------------------------------

    fun buildZoneTemplateReport(
        input: ZoneReportInput,
        language: String,
    ): String {
        val totalDebris = input.sessions.sumOf { it.totalCount }
        val avgHealth = input.sessions.map { it.healthScore }.average()
        val materialMap = buildMaterialMap(input.sessions)
        val dominantMaterial = materialMap.maxByOrNull { it.value }
        val highRiskCount = countHighRisk(input.sessions)
        val dateRange = formatDateRange(input.sessions)
        val healthLabel = healthLabel(avgHealth)
        val trendLabel = trendLabel(input.trend)
        val sortedDays = input.dayGroups.sortedBy { it.date }

        return buildString {
            appendLine("# OceanGuard AI — Zone Environmental Report")
            appendLine()
            appendLine("**Location:** ${input.locationName}")
            appendLine("**Survey period:** $dateRange")
            appendLine("**Sessions analysed:** ${input.sessions.size}")
            appendLine("**Survey days:** ${sortedDays.size}")
            appendLine("**Overall trend:** $trendLabel")
            appendLine("**Generated by:** OceanGuard AI v1.0 (Template Report)")
            appendLine()
            appendLine("---")
            appendLine()
            appendLine("## Zone Overview")
            appendLine()
            appendLine(
                "This report analyses **${input.sessions.size} survey session(s)** collected over " +
                "**${sortedDays.size} day(s)** at **${input.locationName}**. A total of " +
                "**$totalDebris debris item(s)** were identified. The mean health score is " +
                "**${String.format("%.1f", avgHealth)}/100** ($healthLabel), with an overall trend " +
                "classified as **$trendLabel**."
            )
            appendLine()
            appendLine("---")
            appendLine()
            appendLine("## Temporal Evolution")
            appendLine()
            appendTemporalEvolution(sortedDays)
            appendLine()
            appendTrendAssessment(sortedDays, input.trend)
            appendLine()
            appendLine("---")
            appendLine()
            appendLine("## Key Findings")
            appendLine()
            appendKeyFindings(dominantMaterial, highRiskCount, materialMap)
            appendLine()
            appendLine("---")
            appendLine()
            appendLine("## Recommendations")
            appendLine()
            val recs = buildRecommendations(dominantMaterial?.key, avgHealth, highRiskCount)
            recs.forEachIndexed { i, rec -> appendLine("${i + 1}. $rec") }
            appendLine()
            appendLine("---")
            appendLine()
            appendLine("*This report was generated automatically by OceanGuard AI. For AI-assisted narrative " +
                "analysis, deploy the AI model to the device and regenerate.*")
        }.trimEnd()
    }

    // -----------------------------------------------------------------
    // No-data report
    // -----------------------------------------------------------------

    fun buildNoDataReport(language: String): String {
        val languageName = LANGUAGE_NAMES[language] ?: "English"
        return buildString {
            appendLine("# OceanGuard AI — Marine Debris Survey Report")
            appendLine()
            appendLine("**Language:** $languageName")
            appendLine()
            appendLine("No detection sessions are available to generate a report.")
            appendLine()
            appendLine("Capture at least one underwater image using the camera or gallery import, " +
                "run the debris detection analysis, and save the session. Then return here to " +
                "generate your environmental report.")
        }.trimEnd()
    }

    // -----------------------------------------------------------------
    // Mock report (UI testing)
    // -----------------------------------------------------------------

    fun buildMockReport(): String = """# OceanGuard AI — Marine Debris Survey Report

**Survey period:** 2026-02-01 08:30 — 2026-02-22 17:45
**Sessions analysed:** 12
**Generated by:** OceanGuard AI v1.0 (Sample Report)

---

## Overview

This report summarises the findings from **12 underwater debris detection sessions** conducted along the coastal zone of the Mediterranean Sea between 1 February and 22 February 2026. A total of **47 debris items** were identified across all survey images. The mean ecosystem health score for the surveyed area is **54.3/100**, classified as **fair**, indicating notable pollution levels that may be affecting local biodiversity.

---

## Key Findings

### Debris Composition

The most prevalent debris material was **Plastic** (28 items).

**Full material breakdown:** Plastic: 28, Metal: 8, Fabric: 6, Rubber: 3, Other: 2

### Risk Assessment

A total of **19 high-risk item(s)** were detected, posing elevated threats of entanglement, ingestion, or chemical contamination to marine fauna.

---

## Recommendations

1. Launch a targeted plastic-retrieval dive operation in the surveyed area.
2. Establish a long-term monitoring programme with monthly survey sessions.
3. Prioritise the removal of the 19 high-risk item(s) identified in this survey.

---

*This is a sample report for demonstration purposes.*""".trimIndent()

    // -----------------------------------------------------------------
    // Shared helpers
    // -----------------------------------------------------------------

    private fun StringBuilder.appendTemporalEvolution(
        sortedDays: List<com.oceanguard.ai.data.DayGroup>,
    ) {
        sortedDays.forEachIndexed { i, day ->
            val dayMaterials = buildMaterialMapFromSessions(day.sessions)
            val dominant = dayMaterials.maxByOrNull { it.value }
            appendLine(
                "**${DAY_FORMAT.format(day.date)}** — ${day.sessions.size} session(s), " +
                "${day.totalDebris} item(s), health score: ${day.avgHealthScore}/100" +
                (dominant?.let { " (dominant: ${it.key.name.replace("_", " ")})" } ?: "")
            )
            if (i < sortedDays.size - 1) appendLine()
        }
    }

    private fun StringBuilder.appendTrendAssessment(
        sortedDays: List<com.oceanguard.ai.data.DayGroup>,
        trend: HealthTrend,
    ) {
        if (sortedDays.size < 2) return
        val first = sortedDays.first()
        val last = sortedDays.last()
        val delta = last.avgHealthScore - first.avgHealthScore
        val direction = if (delta > 0) "improved" else if (delta < 0) "declined" else "remained stable"
        appendLine(
            "Between ${DAY_FORMAT.format(first.date)} and ${DAY_FORMAT.format(last.date)}, " +
            "the health score $direction from **${first.avgHealthScore}** to " +
            "**${last.avgHealthScore}** (${if (delta >= 0) "+$delta" else "$delta"} points), " +
            "indicating a **${trendLabel(trend).lowercase()}** trajectory."
        )
    }

    private fun StringBuilder.appendKeyFindings(
        dominantMaterial: Map.Entry<DebrisMaterial, Int>?,
        highRiskCount: Int,
        materialMap: Map<DebrisMaterial, Int>,
    ) {
        dominantMaterial?.let { (mat, count) ->
            appendLine(
                "The most prevalent material was **${mat.name.replace("_", " ")}** ($count items)."
            )
            appendLine()
        }
        appendLine("**Full material breakdown:** ${formatMaterialBreakdown(materialMap)}")
        appendLine()
        if (highRiskCount > 0) {
            appendLine(
                "**$highRiskCount high-risk item(s)** were detected (risk score >= 4/5)."
            )
        } else {
            appendLine("No high-risk items were identified.")
        }
    }

    internal fun buildMaterialMap(sessions: List<DetectionSession>): Map<DebrisMaterial, Int> {
        val map = mutableMapOf<DebrisMaterial, Int>()
        sessions.forEach { s ->
            s.debrisList.forEach { d ->
                map[d.material] = (map[d.material] ?: 0) + 1
            }
        }
        return map
    }

    private fun buildMaterialMapFromSessions(
        sessions: List<DetectionSession>,
    ): Map<DebrisMaterial, Int> = buildMaterialMap(sessions)

    internal fun countHighRisk(sessions: List<DetectionSession>): Int =
        sessions.sumOf { s -> s.debrisList.count { it.getRiskScore() >= 4 } }

    private fun formatDateRange(sessions: List<DetectionSession>): String {
        val sorted = sessions.sortedBy { it.timestamp }
        return if (sorted.isNotEmpty()) {
            "${DATE_FORMAT.format(sorted.first().timestamp)} — ${DATE_FORMAT.format(sorted.last().timestamp)}"
        } else "N/A"
    }

    private fun formatMaterialBreakdown(materialMap: Map<DebrisMaterial, Int>): String {
        return if (materialMap.isNotEmpty()) {
            materialMap.entries.sortedByDescending { it.value }.joinToString(", ") { (mat, count) ->
                "${mat.name.replace("_", " ").lowercase().replaceFirstChar { it.uppercase() }}: $count"
            }
        } else "No material data available"
    }

    private fun healthLabel(score: Double): String = when {
        score >= 80 -> "excellent"
        score >= 60 -> "good"
        score >= 40 -> "fair"
        score >= 20 -> "poor"
        else -> "critical"
    }

    internal fun healthDescription(score: Double): String = when {
        score >= 80 -> "minimal anthropogenic impact with a healthy marine ecosystem"
        score >= 60 -> "moderate debris presence with generally stable ecosystem conditions"
        score >= 40 -> "notable pollution levels that may be affecting local biodiversity"
        score >= 20 -> "severe debris accumulation with likely adverse effects on marine life"
        else -> "critical pollution levels requiring immediate remediation"
    }

    private fun trendLabel(trend: HealthTrend): String = when (trend) {
        HealthTrend.IMPROVING -> "Improving"
        HealthTrend.DEGRADING -> "Degrading"
        HealthTrend.STABLE -> "Stable"
    }

    internal fun buildRecommendations(
        dominantMaterial: DebrisMaterial?,
        avgHealth: Double,
        highRiskCount: Int,
    ): List<String> {
        val recs = mutableListOf<String>()
        recs.add(when (dominantMaterial) {
            DebrisMaterial.PLASTIC, null ->
                "Launch a targeted plastic-retrieval dive operation in the surveyed area, " +
                "prioritising single-use items (bottles, bags, packaging) which have the highest " +
                "ingestion risk for sea turtles and seabirds."
            DebrisMaterial.FISHING_NET, DebrisMaterial.FABRIC ->
                "Coordinate with local fishing cooperatives to establish a ghost-gear retrieval " +
                "programme. Derelict nets represent the greatest entanglement risk to marine megafauna."
            DebrisMaterial.METAL ->
                "Partner with dive clubs and port authorities to organise a heavy-debris removal " +
                "operation. Metal debris causes localised habitat destruction and can leach toxins."
            DebrisMaterial.RUBBER ->
                "Identify the source of rubber debris (tyres, seals, equipment) and engage with " +
                "upstream industries to enforce responsible disposal."
            DebrisMaterial.GLASS ->
                "Schedule a fine-debris sweep of the surveyed area to collect glass fragments, " +
                "which pose acute injury risk to benthic species and divers alike."
            DebrisMaterial.OTHER ->
                "Conduct a detailed debris characterisation study to identify the dominant materials " +
                "present before designing a tailored removal strategy."
        })
        if (avgHealth < 60) {
            recs.add(
                "Establish a long-term monitoring programme with monthly survey sessions at this " +
                "location to track remediation progress. Set a target health score of 70/100 within " +
                "12 months and adjust intervention intensity accordingly."
            )
        } else {
            recs.add(
                "Maintain the current monitoring frequency and share survey results with regional " +
                "environmental agencies to contribute to national marine pollution databases."
            )
        }
        if (highRiskCount > 0) {
            recs.add(
                "Prioritise the removal of the $highRiskCount high-risk item(s) identified in this " +
                "survey (risk score 4–5). These objects should be collected before the next tidal cycle."
            )
        } else {
            recs.add(
                "Engage the local community through citizen science dive events to maintain debris " +
                "levels and raise awareness of the impact of land-based pollution on coastal ecosystems."
            )
        }
        return recs
    }
}
