package com.oceanguard.ai.inference.species

import android.graphics.Bitmap

/**
 * Result of a VLM-based species description or confirmation step.
 *
 * @param description     Free-text description generated by the VLM.
 * @param confirmedKey    If the VLM confirmed the RAG top-1 hypothesis,
 *                        this is the confirmed speciesKey; null otherwise.
 * @param contradicted    True if the VLM strongly contradicts the top-1 RAG
 *                        hypothesis (triggers demotion to RAG_TENTATIVE).
 */
data class SpeciesIdResult(
    val description: String,
    val confirmedKey: String? = null,
    val contradicted: Boolean = false,
)

/**
 * VLM-based organism description and RAG hypothesis confirmation.
 *
 * ## Role in the pipeline
 *
 * After [SpeciesReferenceIndex.search] returns a top-k candidate list:
 *  - If top-1 score ≥ τ_alta + margin ≥ δ: call [confirmOrDescribe] with the
 *    top-1 scientificName to let the VLM confirm or contradict.
 *  - If score is tentative or unknown: call [describeOpenVocab] for open-vocab
 *    identification (cola larga / "no catalogada").
 *
 * The VLM is run at low temperature to minimise hallucination.
 *
 * ## Current status: STUB
 *
 * TODO(Phase 2): implement by wiring [com.oceanguard.ai.inference.LiteRTTextEngine]
 *   (Gemma 4) or [com.oceanguard.ai.inference.LlamaVisionEngine] (Qwen).
 *   Use a dedicated "organism mode" system prompt (distinct from the debris
 *   system prompt — NEVER modify the debris system prompt file).
 *   Inject geographic context: "Photo taken in <ecoregionName> (<realmName>)"
 *   to bias naming toward regionally plausible species.
 *   See plan section §6 for the exact prompt and contradiction-detection logic.
 */
class SpeciesDescriber {

    /**
     * Ask the VLM to confirm or refute the [hypothesisScientificName] given
     * the [crop] bitmap, optionally with geographic context from [region].
     *
     * Returns a [SpeciesIdResult] with [SpeciesIdResult.confirmedKey] set if
     * the VLM agrees, or [SpeciesIdResult.contradicted] = true if it disagrees.
     *
     * STUB — always confirms the hypothesis without running VLM inference.
     */
    @Suppress("UnusedParameter")
    suspend fun confirmOrDescribe(
        crop: Bitmap,
        hypothesisKey: String,
        hypothesisScientificName: String,
        region: MarineRegion? = null,
        language: String = "en",
    ): SpeciesIdResult {
        // TODO(Phase 2): invoke LiteRTTextEngine.generateWithImage() with organism prompt
        return SpeciesIdResult(
            description   = "VLM description pending — Phase 2 implementation.",
            confirmedKey  = hypothesisKey,
            contradicted  = false,
        )
    }

    /**
     * Open-vocabulary description for an organism that did not match any
     * catalogued species (score < τ_baja or empty catalogue).
     *
     * Returns a [SpeciesIdResult] with [SpeciesIdResult.confirmedKey] = null
     * and [SpeciesIdResult.description] populated by the VLM.
     *
     * STUB — returns a placeholder description.
     */
    @Suppress("UnusedParameter")
    suspend fun describeOpenVocab(
        crop: Bitmap,
        region: MarineRegion? = null,
        language: String = "en",
    ): SpeciesIdResult {
        // TODO(Phase 2): invoke LiteRTTextEngine.generateWithImage() with open-vocab organism prompt
        return SpeciesIdResult(
            description  = "Open-vocabulary description pending — Phase 2 implementation.",
            confirmedKey = null,
            contradicted = false,
        )
    }
}
