package com.oceanguard.ai.inference.species

/**
 * Result of a VLM-based species description or confirmation step.
 *
 * Produced by [SpeciesDescriber] and consumed by [SpeciesIdentifier].
 *
 * @param description     Free-text description generated by the VLM.
 * @param confirmedKey    The speciesKey the VLM confirmed; null when the VLM
 *                        did not confirm the RAG top-1 or for open-vocab IDs.
 * @param contradicted    True when the VLM strongly contradicts the top-1 RAG
 *                        hypothesis. The orchestrator should demote the result
 *                        to [com.oceanguard.ai.data.species.SpeciesIdSource.RAG_TENTATIVE].
 * @param freeLabel       For open-vocabulary identifications: the organism
 *                        name the VLM suggested (may be common or scientific).
 *                        Null when the VLM was invoked in confirmation mode.
 */
data class SpeciesIdResult(
    val description: String,
    val confirmedKey: String? = null,
    val contradicted: Boolean = false,
    val freeLabel: String? = null,
)
