"""
_med_candidates.py — Curated Mediterranean marine species candidate list.

Iconic / common / well-photographed Mediterranean species across taxonomic
groups, used to expand taxon_list.yaml. Each tuple is:

    (scientific_name, group, cosmopolitan)

`cosmopolitan=True` flags wide-ranging species (turtles, cetaceans, big sharks,
tunas, sunfish, etc.) that are exempt from the biogeographic pre-filter.

This is a HELPER (not committed as pipeline). Names verified against WoRMS at
resolve time by resolve_candidates.py.
"""

from __future__ import annotations

# (scientific_name, group, cosmopolitan)
CANDIDATES: list[tuple[str, str, bool]] = [
    # === BONY FISH ===
    ("Sparus aurata", "bony_fish", False),
    ("Diplodus sargus", "bony_fish", False),
    ("Diplodus vulgaris", "bony_fish", False),
    ("Diplodus puntazzo", "bony_fish", False),
    ("Diplodus annularis", "bony_fish", False),
    ("Sarpa salpa", "bony_fish", False),
    ("Oblada melanura", "bony_fish", False),
    ("Boops boops", "bony_fish", False),
    ("Spondyliosoma cantharus", "bony_fish", False),
    ("Lithognathus mormyrus", "bony_fish", False),
    ("Pagrus pagrus", "bony_fish", False),
    ("Pagellus erythrinus", "bony_fish", False),
    ("Dentex dentex", "bony_fish", False),
    ("Serranus cabrilla", "bony_fish", False),
    ("Serranus scriba", "bony_fish", False),
    ("Symphodus tinca", "bony_fish", False),
    ("Symphodus mediterraneus", "bony_fish", False),
    ("Labrus merula", "bony_fish", False),
    ("Labrus viridis", "bony_fish", False),
    ("Thalassoma pavo", "bony_fish", False),
    ("Sparisoma cretense", "bony_fish", False),
    ("Chromis chromis", "bony_fish", False),
    ("Sciaena umbra", "bony_fish", False),
    ("Umbrina cirrosa", "bony_fish", False),
    ("Apogon imberbis", "bony_fish", False),
    ("Mullus barbatus", "bony_fish", False),
    ("Scorpaena scrofa", "bony_fish", False),
    ("Scorpaena porcus", "bony_fish", False),
    ("Trachinus draco", "bony_fish", False),
    ("Uranoscopus scaber", "bony_fish", False),
    ("Trachurus trachurus", "bony_fish", False),
    ("Seriola dumerili", "bony_fish", False),
    ("Sphyraena sphyraena", "bony_fish", False),
    ("Belone belone", "bony_fish", False),
    ("Atherina hepsetus", "bony_fish", False),
    ("Sardina pilchardus", "bony_fish", False),
    ("Engraulis encrasicolus", "bony_fish", False),
    ("Mugil cephalus", "bony_fish", False),
    ("Chelon labrosus", "bony_fish", False),
    ("Conger conger", "bony_fish", False),
    ("Muraena helena", "bony_fish", False),
    ("Anguilla anguilla", "bony_fish", False),
    ("Gobius niger", "bony_fish", False),
    ("Tripterygion delaisi", "bony_fish", False),
    ("Parablennius gattorugine", "bony_fish", False),
    ("Lophius piscatorius", "bony_fish", False),
    ("Zeus faber", "bony_fish", False),
    ("Phycis phycis", "bony_fish", False),
    ("Merluccius merluccius", "bony_fish", False),
    ("Solea solea", "bony_fish", False),
    ("Bothus podas", "bony_fish", False),
    ("Dactylopterus volitans", "bony_fish", False),
    ("Syngnathus acus", "bony_fish", False),
    ("Hippocampus hippocampus", "bony_fish", False),
    ("Aphanius fasciatus", "bony_fish", False),
    ("Coryphaena hippurus", "bony_fish", True),
    ("Thunnus thynnus", "bony_fish", True),
    ("Thunnus alalunga", "bony_fish", True),
    ("Euthynnus alletteratus", "bony_fish", True),
    ("Sarda sarda", "bony_fish", True),
    ("Scomber scombrus", "bony_fish", True),
    ("Xiphias gladius", "bony_fish", True),

    # === SHARKS / RAYS ===
    ("Scyliorhinus canicula", "shark_ray", False),
    ("Mustelus mustelus", "shark_ray", False),
    ("Galeus melastomus", "shark_ray", False),
    ("Squalus acanthias", "shark_ray", True),
    ("Squatina squatina", "shark_ray", False),
    ("Carcharodon carcharias", "shark_ray", True),
    ("Isurus oxyrinchus", "shark_ray", True),
    ("Prionace glauca", "shark_ray", True),
    ("Cetorhinus maximus", "shark_ray", True),
    ("Alopias vulpinus", "shark_ray", True),
    ("Raja clavata", "shark_ray", False),
    ("Raja asterias", "shark_ray", False),
    ("Dasyatis pastinaca", "shark_ray", False),
    ("Pteroplatytrygon violacea", "shark_ray", True),
    ("Myliobatis aquila", "shark_ray", False),
    ("Torpedo marmorata", "shark_ray", False),
    ("Aetomylaeus bovinus", "shark_ray", False),

    # === SEA TURTLES (cosmopolitan) ===
    ("Eretmochelys imbricata", "turtle", True),
    ("Lepidochelys kempii", "turtle", True),

    # === MARINE MAMMALS (cosmopolitan) ===
    ("Stenella coeruleoalba", "mammal", True),
    ("Delphinus delphis", "mammal", True),
    ("Grampus griseus", "mammal", True),
    ("Globicephala melas", "mammal", True),
    ("Physeter macrocephalus", "mammal", True),
    ("Ziphius cavirostris", "mammal", True),
    ("Balaenoptera physalus", "mammal", True),
    ("Monachus monachus", "mammal", False),

    # === CEPHALOPODS ===
    ("Sepia elegans", "cephalopod", False),
    ("Loligo vulgaris", "cephalopod", False),
    ("Eledone moschata", "cephalopod", False),
    ("Eledone cirrhosa", "cephalopod", False),
    ("Argonauta argo", "cephalopod", True),

    # === OTHER MOLLUSCS ===
    ("Charonia lampas", "mollusc", False),
    ("Hexaplex trunculus", "mollusc", False),
    ("Bolinus brandaris", "mollusc", False),
    ("Cerithium vulgatum", "mollusc", False),
    ("Patella ferruginea", "mollusc", False),
    ("Cypraea spurca", "mollusc", False),
    ("Mytilus galloprovincialis", "mollusc", False),
    ("Ostrea edulis", "mollusc", False),
    ("Spondylus gaederopus", "mollusc", False),
    ("Flabellina affinis", "mollusc", False),
    ("Cratena peregrina", "mollusc", False),
    ("Hypselodoris picta", "mollusc", False),
    ("Felimare picta", "mollusc", False),
    ("Peltodoris atromaculata", "mollusc", False),
    ("Aplysia punctata", "mollusc", False),

    # === ECHINODERMS ===
    ("Arbacia lixula", "echinoderm", False),
    ("Sphaerechinus granularis", "echinoderm", False),
    ("Echinaster sepositus", "echinoderm", False),
    ("Marthasterias glacialis", "echinoderm", False),
    ("Coscinasterias tenuispina", "echinoderm", False),
    ("Astropecten aranciacus", "echinoderm", False),
    ("Ophioderma longicauda", "echinoderm", False),
    ("Holothuria tubulosa", "echinoderm", False),
    ("Holothuria forskali", "echinoderm", False),
    ("Antedon mediterranea", "echinoderm", False),

    # === CNIDARIANS (corals / anemones / jellies / gorgonians) ===
    ("Corallium rubrum", "cnidarian", False),
    ("Paramuricea clavata", "cnidarian", False),
    ("Eunicella singularis", "cnidarian", False),
    ("Eunicella cavolini", "cnidarian", False),
    ("Cladocora caespitosa", "cnidarian", False),
    ("Astroides calycularis", "cnidarian", False),
    ("Balanophyllia europaea", "cnidarian", False),
    ("Parazoanthus axinellae", "cnidarian", False),
    ("Anemonia viridis", "cnidarian", False),
    ("Actinia equina", "cnidarian", False),
    ("Condylactis aurantiaca", "cnidarian", False),
    ("Cerianthus membranaceus", "cnidarian", False),
    ("Pelagia noctiluca", "cnidarian", True),
    ("Cotylorhiza tuberculata", "cnidarian", False),
    ("Rhizostoma pulmo", "cnidarian", False),
    ("Velella velella", "cnidarian", True),
    ("Chrysaora hysoscella", "cnidarian", True),

    # === CRUSTACEANS ===
    ("Palinurus elephas", "crustacean", False),
    ("Homarus gammarus", "crustacean", False),
    ("Scyllarides latus", "crustacean", False),
    ("Maja squinado", "crustacean", False),
    ("Carcinus aestuarii", "crustacean", False),
    ("Pachygrapsus marmoratus", "crustacean", False),
    ("Eriphia verrucosa", "crustacean", False),
    ("Dardanus arrosor", "crustacean", False),
    ("Pagurus prideaux", "crustacean", False),
    ("Palaemon elegans", "crustacean", False),
    ("Stenopus spinosus", "crustacean", False),
    ("Lysmata seticaudata", "crustacean", False),
    ("Nephrops norvegicus", "crustacean", False),
    ("Squilla mantis", "crustacean", False),
    ("Balanus perforatus", "crustacean", False),

    # === SPONGES ===
    ("Spongia officinalis", "sponge", False),
    ("Aplysina aerophoba", "sponge", False),
    ("Axinella polypoides", "sponge", False),
    ("Petrosia ficiformis", "sponge", False),
    ("Clathrina clathrus", "sponge", False),
    ("Chondrosia reniformis", "sponge", False),
    ("Crambe crambe", "sponge", False),

    # === SEAGRASSES / MACROALGAE ===
    ("Cymodocea nodosa", "seagrass_algae", False),
    ("Zostera marina", "seagrass_algae", False),
    ("Caulerpa prolifera", "seagrass_algae", False),
    ("Codium bursa", "seagrass_algae", False),
    ("Acetabularia acetabulum", "seagrass_algae", False),
    ("Halimeda tuna", "seagrass_algae", False),
    ("Padina pavonica", "seagrass_algae", False),
    ("Cystoseira amentacea", "seagrass_algae", False),
    ("Sargassum vulgare", "seagrass_algae", False),
    ("Corallina officinalis", "seagrass_algae", False),
    ("Asparagopsis armata", "seagrass_algae", False),
    ("Lithophyllum byssoides", "seagrass_algae", False),

    # === TUNICATES / BRYOZOANS / WORMS (iconic Med fauna) ===
    ("Halocynthia papillosa", "tunicate", False),
    ("Clavelina lepadiformis", "tunicate", False),
    ("Microcosmus sabatieri", "tunicate", False),
    ("Sabella spallanzanii", "annelid", False),
    ("Protula tubularia", "annelid", False),
    ("Bonellia viridis", "annelid", False),
]
