package com.oceanguard.ai.utils

import android.content.Context
import android.graphics.BitmapFactory
import android.net.Uri
import android.util.Log
import com.oceanguard.ai.data.DetectionSession
import com.oceanguard.ai.data.GeneratedReport
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * Renders a professional PDF report with header, stats, body text,
 * and embedded session images using [PdfPageCanvas].
 */
object PdfReportExporter {

    private const val TAG = "PdfReportExporter"
    private const val MAX_IMAGES = 6
    private const val IMAGE_MAX_WIDTH = 800

    private val dateFormat = SimpleDateFormat("dd MMM yyyy, HH:mm", Locale.getDefault())
    private val fileTimestamp = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.getDefault())

    suspend fun exportReport(
        context: Context,
        report: GeneratedReport,
        sessions: List<DetectionSession>,
    ): File? = withContext(Dispatchers.IO) {
        try {
            val dir = File(context.cacheDir, "exports").also { it.mkdirs() }
            val safeName = (report.locationName ?: "report")
                .replace(Regex("[^a-zA-Z0-9_-]"), "_").take(40)
            val file = File(dir, "oceanguard_${safeName}_${fileTimestamp.format(Date())}.pdf")

            val pdf = PdfPageCanvas(file)

            // 1. Header band
            pdf.drawHeaderBand(
                title = "OceanGuard Environmental Report",
                subtitle = report.locationName,
            )

            // 2. Metadata
            drawMetadata(pdf, report)

            pdf.drawSeparator()

            // 3. Stats summary table
            if (sessions.isNotEmpty()) {
                drawStatsTable(pdf, report, sessions)
                pdf.addSpacing(4)
            }

            // 4. Report body (markdown parsing)
            drawReportBody(pdf, report.text)

            // 5. Embedded images
            if (sessions.isNotEmpty()) {
                drawSessionImages(context, pdf, sessions)
            }

            // 6. Material breakdown table
            if (sessions.isNotEmpty()) {
                drawMaterialBreakdown(pdf, sessions)
            }

            // 7. Footer
            pdf.addSpacing(12)
            pdf.drawSeparator()
            pdf.drawCaption("Generated by OceanGuard AI — ${dateFormat.format(Date())}")

            pdf.finish()
            Log.i(TAG, "PDF exported: ${file.absolutePath} (${file.length() / 1024}KB)")
            file
        } catch (e: Exception) {
            Log.e(TAG, "PDF export failed", e)
            null
        }
    }

    // -- Sections -------------------------------------------------------------

    private fun drawMetadata(pdf: PdfPageCanvas, report: GeneratedReport) {
        val lines = buildList {
            add("Date: ${dateFormat.format(report.timestamp)}")
            report.locationName?.let { add("Location: $it") }
            if (report.centroidLat != null && report.centroidLon != null) {
                add("Coordinates: ${String.format("%.4f", report.centroidLat)}, ${String.format("%.4f", report.centroidLon)}")
            }
            add("Sessions analyzed: ${report.sessionCount}")
            add("Analysis: ${if (report.usedAi) "AI-powered (Gemma 3n)" else "Template-based"}")
            add("Language: ${report.language.uppercase()}")
        }
        for (line in lines) {
            pdf.drawParagraph(line)
        }
    }

    private fun drawStatsTable(
        pdf: PdfPageCanvas,
        report: GeneratedReport,
        sessions: List<DetectionSession>,
    ) {
        val totalDebris = sessions.sumOf { it.totalCount }
        val avgHealth = if (sessions.isNotEmpty()) sessions.map { it.healthScore }.average() else 0.0
        val materialMap = mutableMapOf<String, Int>()
        sessions.forEach { s ->
            s.debrisList.forEach { d ->
                materialMap[d.material.name] = (materialMap[d.material.name] ?: 0) + 1
            }
        }
        val dominant = materialMap.maxByOrNull { it.value }?.key ?: "N/A"
        val highRisk = sessions.sumOf { s -> s.debrisList.count { it.getRiskScore() >= 4 } }

        pdf.drawSubtitle("Survey Statistics")
        pdf.drawTable(
            headers = listOf("Metric", "Value"),
            rows = listOf(
                listOf("Total debris items", totalDebris.toString()),
                listOf("Avg. health score", String.format("%.1f / 100", avgHealth)),
                listOf("Dominant material", dominant.replace("_", " ")),
                listOf("High-risk items", highRisk.toString()),
                listOf("Survey sessions", report.sessionCount.toString()),
            ),
        )
    }

    private fun drawReportBody(pdf: PdfPageCanvas, text: String) {
        val lines = text.lines()
        for (line in lines) {
            val trimmed = line.trim()
            when {
                trimmed.startsWith("## ") -> pdf.drawSubtitle(trimmed.removePrefix("## "))
                trimmed.startsWith("# ") -> pdf.drawSubtitle(trimmed.removePrefix("# "))
                trimmed.startsWith("**") && trimmed.endsWith("**") ->
                    pdf.drawBoldParagraph(trimmed.removeSurrounding("**"))
                trimmed.startsWith("---") || trimmed.startsWith("***") -> pdf.drawSeparator()
                trimmed.isEmpty() -> pdf.addSpacing(4)
                else -> {
                    // Strip inline markdown: **bold** -> bold, *italic* -> italic
                    val clean = trimmed
                        .replace(Regex("""\*\*(.+?)\*\*"""), "$1")
                        .replace(Regex("""\*(.+?)\*"""), "$1")
                        .replace(Regex("""`(.+?)`"""), "$1")
                    pdf.drawParagraph(clean)
                }
            }
        }
    }

    private suspend fun drawSessionImages(
        context: Context,
        pdf: PdfPageCanvas,
        sessions: List<DetectionSession>,
    ) {
        // Prefer annotated thumbnails, fall back to original images
        val imageSessions = sessions
            .filter { !it.thumbnailUri.isNullOrBlank() || it.imageUri.isNotBlank() }
            .take(MAX_IMAGES)

        if (imageSessions.isEmpty()) return

        pdf.addSpacing(8)
        pdf.drawSubtitle("Survey Images")

        for (session in imageSessions) {
            val uriString = session.thumbnailUri ?: session.imageUri
            val bitmap = try {
                loadScaledBitmap(context, uriString)
            } catch (e: Exception) {
                Log.w(TAG, "Could not load image: $uriString", e)
                continue
            } ?: continue

            pdf.drawImage(bitmap)
            val caption = buildString {
                append(dateFormat.format(session.timestamp))
                append(" — ${session.totalCount} debris detected")
                append(" — Health: ${session.healthScore}/100")
            }
            pdf.drawCaption(caption)
            pdf.addSpacing(4)
            bitmap.recycle()
        }
    }

    private fun drawMaterialBreakdown(pdf: PdfPageCanvas, sessions: List<DetectionSession>) {
        val materialMap = mutableMapOf<String, Int>()
        sessions.forEach { s ->
            s.debrisList.forEach { d ->
                materialMap[d.material.name] = (materialMap[d.material.name] ?: 0) + 1
            }
        }
        if (materialMap.isEmpty()) return

        val total = materialMap.values.sum()
        val sorted = materialMap.entries.sortedByDescending { it.value }

        pdf.addSpacing(8)
        pdf.drawSubtitle("Material Breakdown")
        pdf.drawTable(
            headers = listOf("Material", "Count", "Percentage"),
            rows = sorted.map { (material, count) ->
                val pct = if (total > 0) count * 100.0 / total else 0.0
                listOf(
                    material.replace("_", " "),
                    count.toString(),
                    String.format("%.1f%%", pct),
                )
            },
        )
    }

    // -- Image loading --------------------------------------------------------

    private fun loadScaledBitmap(context: Context, uriString: String): android.graphics.Bitmap? {
        val uri = Uri.parse(uriString)
        val inputStream = when (uri.scheme) {
            "file" -> java.io.File(uri.path!!).inputStream()
            else -> context.contentResolver.openInputStream(uri)
        } ?: return null

        // First pass: decode bounds only
        val options = BitmapFactory.Options().apply { inJustDecodeBounds = true }
        inputStream.use { BitmapFactory.decodeStream(it, null, options) }

        // Calculate sample size
        val width = options.outWidth
        val height = options.outHeight
        var sampleSize = 1
        while (width / sampleSize > IMAGE_MAX_WIDTH || height / sampleSize > IMAGE_MAX_WIDTH) {
            sampleSize *= 2
        }

        // Second pass: decode with sample size
        val decodeOptions = BitmapFactory.Options().apply { inSampleSize = sampleSize }
        val stream2 = when (uri.scheme) {
            "file" -> java.io.File(uri.path!!).inputStream()
            else -> context.contentResolver.openInputStream(uri)
        } ?: return null

        return stream2.use { BitmapFactory.decodeStream(it, null, decodeOptions) }
    }
}
