package com.oceanguard.ai.utils

import android.content.Context
import android.graphics.BitmapFactory
import android.net.Uri
import android.util.Log
import com.oceanguard.ai.data.DetectionSession
import com.oceanguard.ai.data.GeneratedReport
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * Renders a professional PDF report with header, stats, body text,
 * and embedded session images using [PdfPageCanvas].
 */
object PdfReportExporter {

    private const val TAG = "PdfReportExporter"
    private const val MAX_IMAGES = 50
    private const val IMAGE_MAX_WIDTH = 800

    private val dateFormat = SimpleDateFormat("dd MMM yyyy, HH:mm", Locale.getDefault())
    private val fileTimestamp = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.getDefault())

    /** Localized labels for PDF sections — keeps the PDF consistent with the report language. */
    private data class PdfLabels(
        val headerTitle: String,
        val date: String, val location: String, val coordinates: String,
        val imagesAnalyzed: String, val analysis: String, val language: String,
        val aiPowered: String, val templateBased: String,
        val surveyStats: String, val metric: String, val value: String,
        val totalDebris: String, val avgHealth: String,
        val dominantMaterial: String, val highRiskItems: String,
        val surveyImages: String, val debrisDetected: String, val health: String,
        val materialBreakdown: String, val material: String, val count: String, val percentage: String,
        val generatedBy: String,
    )

    private fun labelsFor(lang: String): PdfLabels = when (lang) {
        "es" -> PdfLabels("Informe Ambiental OceanGuard", "Fecha", "Ubicación", "Coordenadas", "Imágenes analizadas", "Análisis", "Idioma", "IA", "Basado en plantilla", "Estadísticas del Estudio", "Métrica", "Valor", "Total de residuos", "Salud media", "Material dominante", "Elementos de alto riesgo", "Imágenes del Estudio", "residuos detectados", "Salud", "Desglose por Material", "Material", "Cantidad", "Porcentaje", "Generado por OceanGuard AI")
        "fr" -> PdfLabels("Rapport Environnemental OceanGuard", "Date", "Lieu", "Coordonnées", "Images analysées", "Analyse", "Langue", "IA", "Basé sur modèle", "Statistiques de l'Étude", "Métrique", "Valeur", "Total des déchets", "Santé moyenne", "Matériau dominant", "Éléments à haut risque", "Images de l'Étude", "déchets détectés", "Santé", "Répartition par Matériau", "Matériau", "Quantité", "Pourcentage", "Généré par OceanGuard AI")
        "de" -> PdfLabels("OceanGuard Umweltbericht", "Datum", "Standort", "Koordinaten", "Analysierte Bilder", "Analyse", "Sprache", "KI", "Vorlagenbasiert", "Studienstatistiken", "Metrik", "Wert", "Gesamtabfall", "Durchschn. Gesundheit", "Dominantes Material", "Hochrisikoelemente", "Studienbilder", "Abfall erkannt", "Gesundheit", "Materialaufschlüsselung", "Material", "Anzahl", "Prozent", "Erstellt von OceanGuard AI")
        "it" -> PdfLabels("Rapporto Ambientale OceanGuard", "Data", "Posizione", "Coordinate", "Immagini analizzate", "Analisi", "Lingua", "IA", "Basato su modello", "Statistiche dello Studio", "Metrica", "Valore", "Totale rifiuti", "Salute media", "Materiale dominante", "Elementi ad alto rischio", "Immagini dello Studio", "rifiuti rilevati", "Salute", "Ripartizione per Materiale", "Materiale", "Quantità", "Percentuale", "Generato da OceanGuard AI")
        "pt" -> PdfLabels("Relatório Ambiental OceanGuard", "Data", "Localização", "Coordenadas", "Imagens analisadas", "Análise", "Idioma", "IA", "Baseado em modelo", "Estatísticas do Estudo", "Métrica", "Valor", "Total de resíduos", "Saúde média", "Material dominante", "Itens de alto risco", "Imagens do Estudo", "resíduos detectados", "Saúde", "Distribuição por Material", "Material", "Quantidade", "Porcentagem", "Gerado por OceanGuard AI")
        else -> PdfLabels("OceanGuard Environmental Report", "Date", "Location", "Coordinates", "Images analysed", "Analysis", "Language", "AI-powered", "Template-based", "Survey Statistics", "Metric", "Value", "Total debris items", "Avg. health score", "Dominant material", "High-risk items", "Survey Images", "debris detected", "Health", "Material Breakdown", "Material", "Count", "Percentage", "Generated by OceanGuard AI")
    }

    suspend fun exportReport(
        context: Context,
        report: GeneratedReport,
        sessions: List<DetectionSession>,
    ): File? = withContext(Dispatchers.IO) {
        try {
            val dir = File(context.cacheDir, "exports").also { it.mkdirs() }
            val safeName = (report.locationName ?: "report")
                .replace(Regex("[^a-zA-Z0-9_-]"), "_").take(40)
            val file = File(dir, "oceanguard_${safeName}_${fileTimestamp.format(Date())}.pdf")
            val l = labelsFor(report.language)

            val pdf = PdfPageCanvas(file)

            // 1. Header band
            pdf.drawHeaderBand(
                title = l.headerTitle,
                subtitle = report.locationName,
            )

            // 2. Metadata
            drawMetadata(pdf, report, l)

            pdf.drawSeparator()

            // 3. Stats summary table
            if (sessions.isNotEmpty()) {
                drawStatsTable(pdf, report, sessions, l)
                pdf.addSpacing(4)
            }

            // 4. Report body (markdown parsing)
            drawReportBody(pdf, report.text)

            // 5. Embedded images
            if (sessions.isNotEmpty()) {
                drawSessionImages(context, pdf, sessions, l)
            }

            // 6. Material breakdown table
            if (sessions.isNotEmpty()) {
                drawMaterialBreakdown(pdf, sessions, report.language, l)
            }

            // 7. Footer
            pdf.addSpacing(12)
            pdf.drawSeparator()
            pdf.drawCaption("${l.generatedBy} — ${dateFormat.format(Date())}")

            pdf.finish()
            Log.i(TAG, "PDF exported: ${file.absolutePath} (${file.length() / 1024}KB)")
            file
        } catch (e: Exception) {
            Log.e(TAG, "PDF export failed", e)
            null
        }
    }

    // -- Sections -------------------------------------------------------------

    private fun drawMetadata(pdf: PdfPageCanvas, report: GeneratedReport, l: PdfLabels) {
        val lines = buildList {
            add("${l.date}: ${dateFormat.format(report.timestamp)}")
            report.locationName?.let { add("${l.location}: $it") }
            if (report.centroidLat != null && report.centroidLon != null) {
                add("${l.coordinates}: ${String.format("%.4f", report.centroidLat)}, ${String.format("%.4f", report.centroidLon)}")
            }
            add("${l.imagesAnalyzed}: ${report.sessionCount}")
            add("${l.analysis}: ${if (report.usedAi) l.aiPowered else l.templateBased}")
            add("${l.language}: ${report.language.uppercase()}")
        }
        for (line in lines) {
            pdf.drawParagraph(line)
        }
    }

    private fun drawStatsTable(
        pdf: PdfPageCanvas,
        report: GeneratedReport,
        sessions: List<DetectionSession>,
        l: PdfLabels,
    ) {
        val totalDebris = sessions.sumOf { it.totalCount }
        val avgHealth = if (sessions.isNotEmpty()) sessions.map { it.healthScore }.average() else 0.0
        val materialMap = mutableMapOf<String, Int>()
        sessions.forEach { s ->
            s.debrisList.forEach { d ->
                materialMap[d.material.name] = (materialMap[d.material.name] ?: 0) + 1
            }
        }
        val dominant = materialMap.maxByOrNull { it.value }?.key ?: "N/A"
        val translatedDominant = com.oceanguard.ai.inference.ReportGenerator.translateMaterial(dominant, report.language)
        val highRisk = sessions.sumOf { s -> s.debrisList.count { it.getRiskScore() >= 4 } }

        pdf.drawSubtitle(l.surveyStats)
        pdf.drawTable(
            headers = listOf(l.metric, l.value),
            rows = listOf(
                listOf(l.totalDebris, totalDebris.toString()),
                listOf(l.avgHealth, String.format("%.1f / 100", avgHealth)),
                listOf(l.dominantMaterial, translatedDominant),
                listOf(l.highRiskItems, highRisk.toString()),
                listOf(l.imagesAnalyzed, report.sessionCount.toString()),
            ),
        )
    }

    private val TABLE_ROW_RE = Regex("""^\|(.+)\|$""")
    private val TABLE_SEP_RE = Regex("""^\|[\s:?-]+(\|[\s:?-]+)+\|$""")
    private val BULLET_RE = Regex("""^[-*+]\s+(.+)""")
    private val ORDERED_RE = Regex("""^(\d+)\.\s+(.+)""")

    private fun drawReportBody(pdf: PdfPageCanvas, text: String) {
        val lines = text.lines()
        var i = 0
        while (i < lines.size) {
            val trimmed = lines[i].trim()
            when {
                // Markdown table: header + separator + data rows
                TABLE_ROW_RE.matches(trimmed) && i + 1 < lines.size &&
                    TABLE_SEP_RE.matches(lines[i + 1].trim()) -> {
                    val headers = parseTableCells(trimmed)
                    i += 2 // skip header + separator
                    val rows = mutableListOf<List<String>>()
                    while (i < lines.size && TABLE_ROW_RE.matches(lines[i].trim())) {
                        rows.add(parseTableCells(lines[i].trim()))
                        i++
                    }
                    pdf.drawTable(headers = headers, rows = rows)
                    pdf.addSpacing(4)
                }

                trimmed.startsWith("### ") -> {
                    pdf.drawH3(stripInline(trimmed.removePrefix("### ")))
                    i++
                }
                trimmed.startsWith("## ") -> {
                    pdf.drawSubtitle(stripInline(trimmed.removePrefix("## ")))
                    i++
                }
                trimmed.startsWith("# ") -> {
                    pdf.drawSubtitle(stripInline(trimmed.removePrefix("# ")))
                    i++
                }
                trimmed.startsWith("> ") || trimmed == ">" -> {
                    val quoteLines = mutableListOf<String>()
                    while (i < lines.size) {
                        val ql = lines[i].trim()
                        if (!ql.startsWith("> ") && ql != ">") break
                        quoteLines.add(ql.removePrefix("> ").removePrefix(">").trim())
                        i++
                    }
                    pdf.drawBlockquote(stripInline(quoteLines.joinToString(" ")))
                }
                BULLET_RE.matches(trimmed) -> {
                    val match = BULLET_RE.find(trimmed)!!
                    pdf.drawBulletItem(stripInline(match.groupValues[1]))
                    i++
                }
                ORDERED_RE.matches(trimmed) -> {
                    val match = ORDERED_RE.find(trimmed)!!
                    pdf.drawNumberedItem(match.groupValues[1], stripInline(match.groupValues[2]))
                    i++
                }
                trimmed.startsWith("**") && trimmed.endsWith("**") -> {
                    pdf.drawBoldParagraph(stripInline(trimmed.removeSurrounding("**")))
                    i++
                }
                trimmed.startsWith("---") || trimmed.startsWith("***") -> {
                    pdf.drawSeparator()
                    i++
                }
                trimmed.isEmpty() -> {
                    pdf.addSpacing(4)
                    i++
                }
                else -> {
                    pdf.drawParagraph(stripInline(trimmed))
                    i++
                }
            }
        }
    }

    private fun stripInline(text: String): String = text
        .replace(Regex("""\*\*(.+?)\*\*"""), "$1")
        .replace(Regex("""\*(.+?)\*"""), "$1")
        .replace(Regex("""`(.+?)`"""), "$1")

    private fun parseTableCells(line: String): List<String> {
        return line.trim().removePrefix("|").removeSuffix("|")
            .split("|")
            .map { stripInline(it.trim()) }
    }

    private suspend fun drawSessionImages(
        context: Context,
        pdf: PdfPageCanvas,
        sessions: List<DetectionSession>,
        l: PdfLabels,
    ) {
        // Prefer annotated thumbnails, fall back to original images
        val imageSessions = sessions
            .filter { !it.thumbnailUri.isNullOrBlank() || it.imageUri.isNotBlank() }
            .take(MAX_IMAGES)

        if (imageSessions.isEmpty()) return

        pdf.addSpacing(8)
        pdf.drawSubtitle(l.surveyImages)

        for (session in imageSessions) {
            val uriString = session.thumbnailUri ?: session.imageUri
            val bitmap = try {
                loadScaledBitmap(context, uriString)
            } catch (e: Exception) {
                Log.w(TAG, "Could not load image: $uriString", e)
                continue
            } ?: continue

            pdf.drawImage(bitmap)
            val caption = buildString {
                append(dateFormat.format(session.timestamp))
                append(" — ${session.totalCount} ${l.debrisDetected}")
                append(" — ${l.health}: ${session.healthScore}/100")
            }
            pdf.drawCaption(caption)
            pdf.addSpacing(4)
            bitmap.recycle()
        }
    }

    private fun drawMaterialBreakdown(
        pdf: PdfPageCanvas,
        sessions: List<DetectionSession>,
        language: String,
        l: PdfLabels,
    ) {
        val materialMap = mutableMapOf<String, Int>()
        sessions.forEach { s ->
            s.debrisList.forEach { d ->
                materialMap[d.material.name] = (materialMap[d.material.name] ?: 0) + 1
            }
        }
        if (materialMap.isEmpty()) return

        val total = materialMap.values.sum()
        val sorted = materialMap.entries.sortedByDescending { it.value }

        pdf.addSpacing(8)
        pdf.drawSubtitle(l.materialBreakdown)
        pdf.drawTable(
            headers = listOf(l.material, l.count, l.percentage),
            rows = sorted.map { (material, count) ->
                val pct = if (total > 0) count * 100.0 / total else 0.0
                listOf(
                    com.oceanguard.ai.inference.ReportGenerator.translateMaterial(material, language),
                    count.toString(),
                    String.format("%.1f%%", pct),
                )
            },
        )
    }

    // -- Image loading --------------------------------------------------------

    private fun loadScaledBitmap(context: Context, uriString: String): android.graphics.Bitmap? {
        val uri = Uri.parse(uriString)
        val inputStream = when (uri.scheme) {
            "file" -> java.io.File(uri.path!!).inputStream()
            else -> context.contentResolver.openInputStream(uri)
        } ?: return null

        // First pass: decode bounds only
        val options = BitmapFactory.Options().apply { inJustDecodeBounds = true }
        inputStream.use { BitmapFactory.decodeStream(it, null, options) }

        // Calculate sample size
        val width = options.outWidth
        val height = options.outHeight
        var sampleSize = 1
        while (width / sampleSize > IMAGE_MAX_WIDTH || height / sampleSize > IMAGE_MAX_WIDTH) {
            sampleSize *= 2
        }

        // Second pass: decode with sample size
        val decodeOptions = BitmapFactory.Options().apply { inSampleSize = sampleSize }
        val stream2 = when (uri.scheme) {
            "file" -> java.io.File(uri.path!!).inputStream()
            else -> context.contentResolver.openInputStream(uri)
        } ?: return null

        return stream2.use { BitmapFactory.decodeStream(it, null, decodeOptions) }
    }
}
